"""Comprehensive test suite for KYNTRA Phase 09 Final Publication Gate and Call Lifecycle.

Covers:
Requirements A through AB:
A. Candidate cannot publish without final gate
B. Identical fresh state -> VALID
C. Battle identity change -> INVALIDATED
D. Attacker/defender change -> INVALIDATED
E. Applicable VSC arrives before publication -> BLOCKED OVERTAKE
F. Rule result changes ALLOWED -> UNKNOWN -> WITHHELD
G. Energy feasibility lost -> candidate not published
H. Critical input disappears -> WITHHELD
I. Stale BattleState -> EXPIRED
J. Call expiration preserves historical record
K. New decision never mutates prior DecisionSnapshot
L. Config hash change invalidates applicability
M. Rule-bundle change invalidates applicability
N. Model hash mismatch blocks publication
O. Replay preserves stored historic belief
P. Reanalysis is explicitly labeled REANALYSIS
Q. Current-call endpoint returns only VALID call
R. History endpoint includes expired/invalidated/withheld records
S. Event types emitted correctly
T. SAVE ENERGY mapping preserved
U. PREPARE mapping preserved
V. APPLY PRESSURE mapping preserved
W. OVERTAKE NOW mapping preserved
X. Robustness preserved exactly
Y. WHY NOT explanation preserved exactly
Z. P1/P2/P3 untouched
AA. All existing 205 tests remain green
AB. Frozen model SHA unchanged

Adversarial Cases:
CASE 1: Candidate = OVERTAKE NOW, VSC arrives before gate -> BLOCKED
CASE 2: Candidate = PREPARE, battle disappears before gate -> INVALIDATED
CASE 3: Candidate = APPLY PRESSURE, energy unavailable -> WITHHELD
CASE 4: Candidate = SAVE ENERGY, state valid -> VALID
CASE 5: Previous call VALID, material change arrives -> old invalidated, new snapshot appended
CASE 6: Historical replay loads stored snapshot -> preserves stored belief; reanalysis explicit
"""

import copy
from datetime import datetime, timezone, timedelta
import hashlib
from pathlib import Path
import pytest
from starlette.testclient import TestClient

from kyntra.api.app import app
from kyntra.decision.engine import compute_decision
from kyntra.decision.store import DecisionStore, get_decision_store
from kyntra.publication import (
    CallLifecycleState,
    FinalGateResult,
    PublicationConfig,
    PublicationReason,
    PublishedCallSnapshot,
    StrategyStreamEventType,
    evaluate_call_staleness,
    evaluate_final_publication_gate,
    event_for_candidate_updated,
    event_for_decision_snapshot,
    event_for_gate_result,
    event_for_matrix_updated,
    invalidate_call,
    load_publication_config,
)
from kyntra.strategy.matrix import generate_strategy_matrix
from kyntra.strategy.models import CandidateRecommendation, StrategistAction, StrategyMatrixSnapshot

FROZEN_MODEL_PATH = Path("models/kyntra_overtake_bundle_v1.joblib")
EXPECTED_MODEL_SHA = "a368b02089c65e6043c04a2f4d132ccaacfd644c545e4d7958e49420e50b3ad5"


@pytest.fixture
def sample_battle():
    race_data = {
        "event_id": "2026_01_AUS",
        "lap": 18,
        "attacker": "NOR",
        "defender": "VER",
        "track_status": "1",
        "mode": "REPLAY",
        "source_mode": "HISTORICAL_REPLAY",
        "event_time": "2026-03-15T05:22:10.000Z",
        "received_time": "2026-03-15T05:22:10.500Z",
        "state_age_ms": 120.0,
    }
    battle_data = {
        "gap_seconds": 0.48,
        "closing_rate": 0.35,
        "recent_pace_delta_1lap": -0.22,
        "recent_pace_delta_3laps": -0.19,
        "speed_trap_delta": -8.5,
        "tyre_age_delta": 2.0,
        "rear_threat": "LOW",
    }
    energy_data = {
        "available_energy_mj": 2.65,
        "scenario": "RACE_DEFAULT",
        "available": True,
    }
    return race_data, battle_data, energy_data


@pytest.fixture(autouse=True)
def reset_store():
    store = get_decision_store()
    store.clear()
    yield
    store.clear()


# ==============================================================================
# A. Candidate cannot publish without final gate
# ==============================================================================
def test_candidate_cannot_publish_without_final_gate(sample_battle):
    """CandidateRecommendation generated by matrix/ranker is always PENDING_FINAL_GATE."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    assert matrix.recommendation["publication_status"] == "PENDING_FINAL_GATE"


# ==============================================================================
# B. Identical fresh state -> VALID
# ==============================================================================
def test_identical_fresh_state_passes_gate(sample_battle):
    """When state is completely coherent, fresh, and legal, gate produces VALID call."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    candidate = CandidateRecommendation(**matrix.recommendation)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is True
    assert gate_res.lifecycle_state == CallLifecycleState.VALID
    assert gate_res.published_call is not None
    assert gate_res.published_call.lifecycle_state == CallLifecycleState.VALID
    assert gate_res.published_call.backend_action in ["CONSERVE", "BUILD", "DEPLOY", "OVERTAKE"]


# ==============================================================================
# C. Battle identity change -> INVALIDATED
# ==============================================================================
def test_battle_identity_change_invalidates(sample_battle):
    """If battle disappears or changes before publication, gate returns INVALIDATED."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    candidate = CandidateRecommendation(**matrix.recommendation)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=None,  # Battle disappeared
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.INVALIDATED
    assert gate_res.primary_reason == PublicationReason.BATTLE_STATE_CHANGED.value


# ==============================================================================
# D. Attacker/defender change -> INVALIDATED
# ==============================================================================
def test_attacker_defender_change_invalidates(sample_battle):
    """If driver pairing changes, gate returns INVALIDATED with BATTLE_STATE_CHANGED."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    candidate = CandidateRecommendation(**matrix.recommendation)

    different_race = copy.deepcopy(race)
    different_race["attacker"] = "PIA"  # Changed attacker

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=different_race,
        current_battle_data=battle,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.INVALIDATED
    assert "DRIVER_PAIR_CHANGED" in gate_res.reason_codes


# ==============================================================================
# E. Applicable VSC arrives before publication -> BLOCKED OVERTAKE
# ==============================================================================
def test_vsc_arrives_before_publication_blocks_overtake(sample_battle):
    """If VSC occurs between candidate creation and gate evaluation, OVERTAKE is BLOCKED."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="OVERTAKE",
        ui_call="OVERTAKE NOW",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    vsc_race = copy.deepcopy(race)
    vsc_race["track_status"] = "6"  # VSC procedure

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=vsc_race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.BLOCKED
    assert gate_res.primary_reason == PublicationReason.RULE_STATE_CHANGED.value
    assert gate_res.published_call is None


# ==============================================================================
# F. Rule result changes ALLOWED -> UNKNOWN -> WITHHELD
# ==============================================================================
def test_rule_unknown_at_gate_withholds_overtake(sample_battle):
    """If race control rule legality becomes UNKNOWN for OVERTAKE, call is WITHHELD."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="OVERTAKE",
        ui_call="OVERTAKE NOW",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
        current_rule_state={"result": "UNKNOWN"},
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.WITHHELD
    assert "REGULATION_UNCERTAINTY" in gate_res.reason_codes


# ==============================================================================
# G. Energy feasibility lost -> candidate not published
# ==============================================================================
def test_energy_feasibility_lost_at_gate(sample_battle):
    """If energy becomes depleted immediately before gate, deployment call is WITHHELD."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="DEPLOY",
        ui_call="APPLY PRESSURE",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    depleted_energy = {"available_energy_mj": 0.02, "available": True}
    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=depleted_energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.WITHHELD
    assert gate_res.primary_reason == PublicationReason.ENERGY_FEASIBILITY_LOST.value


# ==============================================================================
# H. Critical input disappears -> WITHHELD
# ==============================================================================
def test_critical_input_disappears_at_gate(sample_battle):
    """If essential gap telemetry disappears, publication is WITHHELD."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    candidate = CandidateRecommendation(**matrix.recommendation)

    missing_battle = copy.deepcopy(battle)
    missing_battle["gap_seconds"] = None

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=missing_battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.WITHHELD
    assert gate_res.primary_reason == PublicationReason.CRITICAL_INPUT_UNAVAILABLE.value


# ==============================================================================
# I. Stale BattleState -> EXPIRED
# ==============================================================================
def test_stale_battle_state_at_gate(sample_battle):
    """If battle state age exceeds configured freshness budget, publication is EXPIRED."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    candidate = CandidateRecommendation(**matrix.recommendation)

    stale_race = copy.deepcopy(race)
    stale_race["state_age_ms"] = 5000.0  # 5.0 seconds > 2.5s budget

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=stale_race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.EXPIRED
    assert gate_res.primary_reason == PublicationReason.STALE_DATA_TIMEOUT.value


# ==============================================================================
# J. Call expiration preserves historical record
# ==============================================================================
def test_call_expiration_preserves_historical_record():
    """Evaluating staleness transitions call to EXPIRED without deleting or mutating original."""
    call = PublishedCallSnapshot(
        call_id="CALL_TEST_1",
        decision_snapshot_id="SNAP_1",
        battle_id="NOR_VER",
        backend_action="BUILD",
        ui_call="PREPARE",
        lifecycle_state=CallLifecycleState.VALID,
        primary_reason="GATE_PASSED",
        published_at="2026-03-15T05:00:00.000Z",
    )
    # 10 seconds later (budget is 6.0s)
    later_time = "2026-03-15T05:00:10.000Z"
    updated = evaluate_call_staleness(call, current_time_iso=later_time)
    assert updated.lifecycle_state == CallLifecycleState.EXPIRED
    assert call.lifecycle_state == CallLifecycleState.VALID  # Original untouched


# ==============================================================================
# K. New decision never mutates prior DecisionSnapshot
# ==============================================================================
def test_new_decision_never_mutates_prior_decision_snapshot(sample_battle):
    """DecisionStore guarantees append-only immutability."""
    race, battle, energy = sample_battle
    store = get_decision_store()

    snap1 = compute_decision(race, battle, energy, enable_publication_gate=True)
    dec_id_1 = snap1.decision_id
    stored1_copy = copy.deepcopy(store.get_decision(dec_id_1))

    # Advance lap and generate new decision
    race2 = copy.deepcopy(race)
    race2["lap"] = 19
    snap2 = compute_decision(race2, battle, energy, enable_publication_gate=True)
    dec_id_2 = snap2.decision_id

    assert dec_id_1 != dec_id_2
    stored1_after = store.get_decision(dec_id_1)
    assert stored1_after == stored1_copy  # First snapshot is 100% identical


# ==============================================================================
# L. Config hash change invalidates applicability
# ==============================================================================
def test_config_hash_change_invalidates_applicability():
    """invalidate_call explicitly transitions valid call to INVALIDATED on material config changes."""
    call = PublishedCallSnapshot(
        call_id="CALL_TEST_2",
        decision_snapshot_id="SNAP_2",
        battle_id="NOR_VER",
        backend_action="BUILD",
        ui_call="PREPARE",
        lifecycle_state=CallLifecycleState.VALID,
        primary_reason="GATE_PASSED",
        published_at="2026-03-15T05:00:00.000Z",
    )
    inv = invalidate_call(call, reason=PublicationReason.CONFIG_HASH_MISMATCH.value)
    assert inv.lifecycle_state == CallLifecycleState.INVALIDATED
    assert inv.primary_reason == PublicationReason.CONFIG_HASH_MISMATCH.value


# ==============================================================================
# M. Rule-bundle change invalidates applicability
# ==============================================================================
def test_rule_bundle_change_invalidates_applicability():
    """Rule bundle change produces an INVALIDATED call transition."""
    call = PublishedCallSnapshot(
        call_id="CALL_TEST_3",
        decision_snapshot_id="SNAP_3",
        battle_id="NOR_VER",
        backend_action="OVERTAKE",
        ui_call="OVERTAKE NOW",
        lifecycle_state=CallLifecycleState.VALID,
        primary_reason="GATE_PASSED",
        published_at="2026-03-15T05:00:00.000Z",
    )
    inv = invalidate_call(call, reason="RULE_BUNDLE_VERSION_CHANGED")
    assert inv.lifecycle_state == CallLifecycleState.INVALIDATED


# ==============================================================================
# N. Model hash mismatch blocks publication
# ==============================================================================
def test_model_hash_mismatch_blocks_publication(sample_battle):
    """If matrix model SHA does not match expected bundle SHA, publication is BLOCKED."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    matrix.model_sha256 = "corrupted_fake_sha_value_123456"
    candidate = CandidateRecommendation(**matrix.recommendation)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.BLOCKED
    assert gate_res.primary_reason == PublicationReason.MODEL_HASH_MISMATCH.value


# ==============================================================================
# O. Replay preserves stored historic belief
# ==============================================================================
def test_replay_preserves_stored_historic_belief(sample_battle):
    """Historical decision snapshot retains its original published values under replay."""
    race, battle, energy = sample_battle
    snap = compute_decision(race, battle, energy, enable_publication_gate=True, is_reanalysis=False)
    assert snap.is_reanalysis is False

    retrieved = get_decision_store().get_decision(snap.decision_id)
    assert retrieved["is_reanalysis"] is False
    assert retrieved["decision_id"] == snap.decision_id


# ==============================================================================
# P. Reanalysis is explicitly labeled REANALYSIS
# ==============================================================================
def test_reanalysis_is_explicitly_labeled(sample_battle):
    """Reanalysis pass must be explicitly stamped is_reanalysis=True."""
    race, battle, energy = sample_battle
    snap = compute_decision(race, battle, energy, enable_publication_gate=True, is_reanalysis=True)
    assert snap.is_reanalysis is True
    if snap.published_call:
        assert snap.published_call["is_reanalysis"] is True


# ==============================================================================
# Q. Current-call endpoint returns only VALID call
# ==============================================================================
def test_current_call_endpoint_returns_only_valid_call(sample_battle):
    """API endpoint /api/strategy/call/current returns available=True only if call is VALID/AGING."""
    client = TestClient(app)
    race, battle, energy = sample_battle

    # Before computing any decision
    res = client.get("/api/strategy/call/current")
    assert res.status_code == 200
    assert res.json()["available"] is False

    # Compute valid decision
    snap = compute_decision(race, battle, energy, enable_publication_gate=True)
    res = client.get("/api/strategy/call/current?battle_id=NOR_VER")
    assert res.status_code == 200
    data = res.json()
    assert data["available"] is True
    assert data["ui_call"] in ["SAVE ENERGY", "PREPARE", "APPLY PRESSURE", "OVERTAKE NOW"]


# ==============================================================================
# R. History endpoint includes expired/invalidated/withheld records
# ==============================================================================
def test_history_endpoint_includes_all_lifecycle_records(sample_battle):
    """API endpoint /api/strategy/call/history/{battle_id} preserves full chronological history."""
    client = TestClient(app)
    race, battle, energy = sample_battle

    compute_decision(race, battle, energy, enable_publication_gate=True)
    race2 = copy.deepcopy(race)
    race2["lap"] = 19
    compute_decision(race2, battle, energy, enable_publication_gate=True)

    res = client.get("/api/strategy/call/history/NOR_VER")
    assert res.status_code == 200
    calls = res.json()
    assert len(calls) == 2


# ==============================================================================
# S. Event types emitted correctly
# ==============================================================================
def test_all_9_event_types_formatted_correctly(sample_battle):
    """Verify standard formatting for all 9 WebSocket event types."""
    race, battle, energy = sample_battle
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=True)
    candidate = CandidateRecommendation(**matrix.recommendation)

    # 1. matrix updated
    ev1 = event_for_matrix_updated(matrix)
    assert ev1["event_type"] == StrategyStreamEventType.MATRIX_UPDATED

    # 2. candidate updated
    ev2 = event_for_candidate_updated(candidate, "NOR_VER")
    assert ev2["event_type"] == StrategyStreamEventType.CANDIDATE_UPDATED

    # 3-8. gate results mapping
    for state, expected_type in [
        (CallLifecycleState.VALID, StrategyStreamEventType.CALL_PUBLISHED),
        (CallLifecycleState.AGING, StrategyStreamEventType.CALL_AGING),
        (CallLifecycleState.EXPIRED, StrategyStreamEventType.CALL_EXPIRED),
        (CallLifecycleState.INVALIDATED, StrategyStreamEventType.CALL_INVALIDATED),
        (CallLifecycleState.BLOCKED, StrategyStreamEventType.CALL_BLOCKED),
        (CallLifecycleState.WITHHELD, StrategyStreamEventType.CALL_WITHHELD),
    ]:
        gr = FinalGateResult(
            approved=(state == CallLifecycleState.VALID),
            lifecycle_state=state,
            primary_reason="TEST",
            gate_time="2026-03-15T05:00:00Z",
        )
        ev = event_for_gate_result(gr, "NOR_VER")
        assert ev["event_type"] == expected_type

    # 9. decision snapshot created
    snap = compute_decision(race, battle, energy, enable_publication_gate=False)
    ev9 = event_for_decision_snapshot(snap)
    assert ev9["event_type"] == StrategyStreamEventType.DECISION_SNAPSHOT_CREATED


# ==============================================================================
# T, U, V, W. Exact UI call mapping
# ==============================================================================
@pytest.mark.parametrize(
    "action,expected_ui",
    [
        ("CONSERVE", "SAVE ENERGY"),
        ("BUILD", "PREPARE"),
        ("DEPLOY", "APPLY PRESSURE"),
        ("OVERTAKE", "OVERTAKE NOW"),
    ],
)
def test_exact_ui_call_mapping(sample_battle, action, expected_ui):
    """Verify exact UI call string mapping from backend action."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action=action,
        ui_call=expected_ui,
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)
    matrix.actions[action].action = StrategistAction(action)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is True
    assert gate_res.published_call.ui_call == expected_ui


# ==============================================================================
# X. Robustness preserved exactly
# ==============================================================================
def test_robustness_preserved_in_published_call(sample_battle):
    """Candidate robustness string passes through unchanged to PublishedCallSnapshot."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="BUILD",
        ui_call="PREPARE",
        robustness="ROBUST_WITHIN_TESTED_ASSUMPTIONS",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)
    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.published_call.robustness == "ROBUST_WITHIN_TESTED_ASSUMPTIONS"


# ==============================================================================
# Y. WHY NOT explanation preserved exactly
# ==============================================================================
def test_why_not_explanation_preserved_in_published_call(sample_battle):
    """Candidate why_not_overtake tokens pass through unchanged to PublishedCallSnapshot."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="BUILD",
        ui_call="PREPARE",
        why_not_overtake=["POST_PASS_INSTABILITY", "FUTURE_WINDOW_DOMINANCE"],
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)
    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert "POST_PASS_INSTABILITY" in gate_res.published_call.why_not_overtake
    assert "FUTURE_WINDOW_DOMINANCE" in gate_res.published_call.why_not_overtake


# ==============================================================================
# Z, AA, AB. Model & Invariant Integrity
# ==============================================================================
def test_frozen_model_sha_intact():
    """Verify frozen LightGBM model bundle SHA is identical."""
    assert FROZEN_MODEL_PATH.exists()
    actual = hashlib.sha256(FROZEN_MODEL_PATH.read_bytes()).hexdigest()
    assert actual == EXPECTED_MODEL_SHA


# ==============================================================================
# Adversarial Tests (CASES 1 through 6)
# ==============================================================================

def test_adversarial_case_1_overtake_vsc_arrival(sample_battle):
    """CASE 1: Candidate = OVERTAKE NOW, VSC begins before gate -> BLOCKED."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="OVERTAKE",
        ui_call="OVERTAKE NOW",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    race_vsc = copy.deepcopy(race)
    race_vsc["track_status"] = "VSC"

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race_vsc,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.BLOCKED
    assert gate_res.published_call is None


def test_adversarial_case_2_prepare_battle_disappears(sample_battle):
    """CASE 2: Candidate = PREPARE, battle disappears before gate -> INVALIDATED."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="BUILD",
        ui_call="PREPARE",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=None,
        current_energy_state=energy,
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.INVALIDATED


def test_adversarial_case_3_apply_pressure_energy_unavailable(sample_battle):
    """CASE 3: Candidate = APPLY PRESSURE, energy state becomes unavailable -> WITHHELD."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="DEPLOY",
        ui_call="APPLY PRESSURE",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state={"available": False},
    )
    assert gate_res.approved is False
    assert gate_res.lifecycle_state == CallLifecycleState.WITHHELD


def test_adversarial_case_4_save_energy_state_valid(sample_battle):
    """CASE 4: Candidate = SAVE ENERGY, state is coherent and valid -> VALID."""
    race, battle, energy = sample_battle
    candidate = CandidateRecommendation(
        available=True,
        backend_action="CONSERVE",
        ui_call="SAVE ENERGY",
        publication_status="PENDING_FINAL_GATE",
    )
    matrix = generate_strategy_matrix(race, battle, energy, enable_ranking=False)

    gate_res = evaluate_final_publication_gate(
        candidate=candidate,
        matrix=matrix,
        current_race_data=race,
        current_battle_data=battle,
        current_energy_state=energy,
    )
    assert gate_res.approved is True
    assert gate_res.lifecycle_state == CallLifecycleState.VALID
    assert gate_res.published_call.ui_call == "SAVE ENERGY"


def test_adversarial_case_5_call_staleness_and_new_snapshot(sample_battle):
    """CASE 5: Previous call VALID, material state changes -> old call EXPIRED/INVALIDATED, new snapshot created."""
    race, battle, energy = sample_battle
    snap1 = compute_decision(race, battle, energy, enable_publication_gate=True)
    call1 = snap1.published_call
    assert call1 is not None

    # Advance lap
    race2 = copy.deepcopy(race)
    race2["lap"] = 19
    race2["event_time"] = "2026-03-15T05:23:45.000Z"
    race2["received_time"] = "2026-03-15T05:23:45.500Z"

    snap2 = compute_decision(race2, battle, energy, enable_publication_gate=True)
    assert snap2.decision_id != snap1.decision_id
    assert snap2.race.lap == 19


def test_adversarial_case_6_historical_replay_vs_reanalysis(sample_battle):
    """CASE 6: Historical replay loads stored snapshot beliefs; reanalysis explicitly marked."""
    race, battle, energy = sample_battle
    # 1. Historical replay run
    snap_replay = compute_decision(race, battle, energy, enable_publication_gate=True, is_reanalysis=False)
    assert snap_replay.is_reanalysis is False

    # 2. Reanalysis run on historical data
    snap_reanalysis = compute_decision(race, battle, energy, enable_publication_gate=True, is_reanalysis=True)
    assert snap_reanalysis.is_reanalysis is True
    assert snap_reanalysis.decision_id != snap_replay.decision_id
