import { useState } from 'react';
import type { ContextWorkspace, DecisionSnapshot, EvidenceInspectionTarget } from '../../types';
import { metric, modelHash, publishedLabel } from '../../domain/presentation';
interface Props { isOpen:boolean; onClose:()=>void; decision:DecisionSnapshot|null; previousDecision?:DecisionSnapshot|null; operatingMode?:string; onOpenEvidence?:(target:EvidenceInspectionTarget)=>void; onNavigateWorkspace?:(workspace:ContextWorkspace)=>void; onSendCommand?:(payload:any)=>void }
const QUERIES=['Why this call?','Why not overtake?','Compare PREPARE and OVERTAKE NOW','What changed?','Show model evidence','Show energy evidence','Show rule state','Show stability evidence','Replay previous decision'];
export function StructuredCopilot({isOpen,onClose,decision,previousDecision,operatingMode,onOpenEvidence,onNavigateWorkspace,onSendCommand}:Props){
  const [query,setQuery]=useState('Why this call?');
  const [input,setInput]=useState('');
  if(!isOpen) return null;
  const call=decision?.published_call, matrix=decision?.strategy_matrix;
  let answer='Choose a supported evidence command.', raw:any=decision, workspace:ContextWorkspace='RACE';
  if(query.toLowerCase().includes('compare')){answer=`PREPARE: ${matrix?.actions?.BUILD?.rule_check?.result || 'UNKNOWN'} rules, ${metric(matrix?.actions?.BUILD?.energy?.after_mj,' MJ')} after action. OVERTAKE NOW: ${matrix?.actions?.OVERTAKE?.rule_check?.result || 'UNKNOWN'} rules, ${metric(matrix?.actions?.OVERTAKE?.energy?.after_mj,' MJ')} after action. Inspect the ranking trace for the reported elimination reasons.`;raw={prepare:matrix?.actions?.BUILD,overtake:matrix?.actions?.OVERTAKE,ranking:matrix?.ranking};workspace='STRATEGY';}
  else if(query.toLowerCase().includes('why not')){answer=(call?.why_not_overtake || []).join(' · ') || 'No why-not-overtake reason was published.';raw={reasons:call?.why_not_overtake,ranking:matrix?.ranking};workspace='STRATEGY';}
  else if(query.toLowerCase().includes('why this')){answer=`${publishedLabel(decision)}. ${(call?.why_selected || []).join(' ') || call?.primary_reason || 'No published rationale.'}`;raw=call;}
  else if(query.toLowerCase().includes('changed')){answer=previousDecision ? `Earlier: ${publishedLabel(previousDecision)}. Current: ${publishedLabel(decision)}. Gap ${metric(previousDecision.battle.gap_seconds,'s')} → ${metric(decision?.battle.gap_seconds,'s')}.` : 'No earlier comparable snapshot captured.';raw={earlier:previousDecision,current:decision};workspace='EVENTS';}
  else if(query.toLowerCase().includes('model')){answer=`Frozen model SHA: ${modelHash(decision) || 'UNKNOWN'}. New inputs are evaluated with fixed weights; P1/P2/P3 describe cumulative pass horizons.`;raw=decision?.overtake;workspace='ANALYSIS';}
  else if(query.toLowerCase().includes('energy')){answer=`Simulated available energy: ${metric(decision?.energy.available_energy_mj,' MJ')}. This is not measured private battery SOC.`;raw=decision?.energy;}
  else if(query.toLowerCase().includes('rule')){answer=`Rule state: ${decision?.compliance.status || 'UNKNOWN'}. ${decision?.compliance.reason_codes.join(' · ') || 'No reason codes reported.'}`;raw=decision?.compliance;}
  else if(query.toLowerCase().includes('stability')){answer=`Stability: ${decision?.stability.verdict || 'UNKNOWN'}. ${decision?.stability.reason || 'No explanation reported.'} Ordinal evidence, not a retention probability.`;raw=decision?.stability;}
  else if(query.toLowerCase().includes('previous')){answer=previousDecision?.race.lap != null && operatingMode==='REPLAY' ? `Previous observed decision is on lap ${previousDecision.race.lap}. Use the seek control below to replay that lap.` : 'An earlier observed decision and replay mode are required.';raw=previousDecision;workspace='EVENTS';}
  return <div className="structured-copilot-overlay" onClick={onClose}><section className="astra-copilot" role="dialog" aria-modal="true" aria-label="KYNTRA Copilot" onClick={e=>e.stopPropagation()}><div className="astra-section-heading"><div><span className="astra-eyebrow">KYNTRA / COMMAND LAYER</span><h2>Ask the evidence.</h2><p>Deterministic queries over the current decision.</p></div><button className="astra-button" onClick={onClose} aria-label="Close Copilot">✕</button></div><form onSubmit={e=>{e.preventDefault();setQuery(input);}}><input autoFocus aria-label="Evidence command" value={input} onChange={e=>setInput(e.target.value)} placeholder="Why this call?"/><button className="astra-button">Execute ↵</button></form><div className="astra-query-grid">{QUERIES.map(q=><button key={q} className={q===query?'active':''} onClick={()=>setQuery(q)}>{q}</button>)}</div><div className="astra-command-result"><span className="astra-eyebrow">{query}</span><p>{answer}</p><small>Snapshot: {decision?.decision_id || 'UNAVAILABLE'} · response follows current evidence</small></div><div className="astra-command-actions"><button className="astra-button" onClick={()=>{onOpenEvidence?.({title:query,value:answer,status:'INFO',provenance:'DERIVED',rawObject:raw || {}});onClose();}}>Inspect evidence ↗</button><button className="astra-button" onClick={()=>{onNavigateWorkspace?.(workspace);onClose();}}>Open {workspace.toLowerCase()} ↗</button>{query.toLowerCase().includes('previous')&&<button className="astra-button" disabled={operatingMode!=='REPLAY'||previousDecision?.race.lap==null} onClick={()=>{onSendCommand?.({action:'seek',lap:previousDecision?.race.lap});onClose();}}>Seek previous lap</button>}</div></section></div>;
}

