"""Typed data models and lifecycle states for the KYNTRA Decision Publication Gate."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class CallLifecycleState(str, Enum):
    """Explicit lifecycle state of a tactical strategy call."""

    PENDING_FINAL_GATE = "PENDING_FINAL_GATE"  # Candidate generated by ranking; final publication gate pending
    VALID = "VALID"                            # Final gate approved against newest coherent race state
    AGING = "AGING"                            # Valid but approaching configured freshness boundary
    EXPIRED = "EXPIRED"                        # Temporal freshness budget exceeded; fresh cycle required
    INVALIDATED = "INVALIDATED"                # Material source-state change makes previous call obsolete
    BLOCKED = "BLOCKED"                        # New rule or race-control status prohibits candidate action
    WITHHELD = "WITHHELD"                      # Uncertainty or missing critical input prevents publication


class PublicationReason(str, Enum):
    """Semantic reason codes for publication gate rulings."""

    GATE_PASSED = "GATE_PASSED"
    BATTLE_STATE_CHANGED = "BATTLE_STATE_CHANGED"
    TEMPORAL_COHERENCE_UNRESOLVED = "TEMPORAL_COHERENCE_UNRESOLVED"
    RULE_STATE_CHANGED = "RULE_STATE_CHANGED"
    ENERGY_STATE_CHANGED = "ENERGY_STATE_CHANGED"
    ENERGY_FEASIBILITY_LOST = "ENERGY_FEASIBILITY_LOST"
    CRITICAL_INPUT_UNAVAILABLE = "CRITICAL_INPUT_UNAVAILABLE"
    STALE_DATA_TIMEOUT = "STALE_DATA_TIMEOUT"
    STRATEGY_TIE = "STRATEGY_TIE"
    CONFIG_HASH_MISMATCH = "CONFIG_HASH_MISMATCH"
    MODEL_HASH_MISMATCH = "MODEL_HASH_MISMATCH"
    REPLAY_HISTORIC_RECORD = "REPLAY_HISTORIC_RECORD"
    REANALYSIS_SUPERSEDED = "REANALYSIS_SUPERSEDED"


class FailureSeverity(str, Enum):
    """Failure impact hierarchy for gate checks."""

    SYSTEM_BLOCKING = "SYSTEM_BLOCKING"        # Critical system integrity fault (e.g. invalid race state)
    DECISION_BLOCKING = "DECISION_BLOCKING"    # Action cannot be approved (e.g. blocked by rule change)
    MODULE_UNAVAILABLE = "MODULE_UNAVAILABLE"  # Non-blocking optional module missing
    INFORMATIONAL = "INFORMATIONAL"            # Telemetry note or telemetry latency advisory


class PublishedCallSnapshot(BaseModel):
    """Authoritative, pit-wall published KYNTRA call."""

    call_id: str
    decision_snapshot_id: str
    matrix_snapshot_id: Optional[str] = None
    battle_id: str
    backend_action: str                        # CONSERVE | BUILD | DEPLOY | OVERTAKE
    ui_call: str                               # SAVE ENERGY | PREPARE | APPLY PRESSURE | OVERTAKE NOW
    lifecycle_state: CallLifecycleState = CallLifecycleState.VALID
    primary_reason: str
    reason_codes: List[str] = Field(default_factory=list)
    published_at: str
    valid_until: Optional[str] = None
    robustness: str = "INSUFFICIENT_INFORMATION"
    why_selected: List[str] = Field(default_factory=list)
    why_not_overtake: List[str] = Field(default_factory=list)
    provenance: Dict[str, Any] = Field(default_factory=dict)
    is_reanalysis: bool = False


class FinalGateResult(BaseModel):
    """Forensic audit of all pre-publication gate checks."""

    approved: bool
    lifecycle_state: CallLifecycleState
    primary_reason: str
    reason_codes: List[str] = Field(default_factory=list)
    gate_time: str
    checks: Dict[str, Dict[str, Any]] = Field(default_factory=dict)
    published_call: Optional[PublishedCallSnapshot] = None
