"""Regulation-constrained Energy Simulator V1 for KYNTRA.

SIMULATION PROVENANCE GUARANTEE:
All energy states and values generated by this simulator are tagged with:
source = TelemetrySource.SIMULATED.
Public FastF1 telemetry does not provide internal battery telemetry; this engine
simulates the official FIA 2026 4.0 MJ usable energy store window, MGU-K power curves,
and recharge ceilings under driver input context.
"""

from datetime import timedelta
from typing import Dict, List, Optional, Tuple, Union
import logging
import pandas as pd

from kyntra.energy.actions import (
    DEFAULT_ACTION_POLICY,
    ActionPolicyConfig,
    TacticalAction,
    compute_target_deployment_power_kw,
)
from kyntra.energy.harvest import (
    DEFAULT_HARVEST_CONFIG,
    HarvestModelConfig,
    calculate_step_harvest_mj,
)
from kyntra.energy.state import EnergyState, TelemetrySource
from kyntra.regulations.compliance import (
    ComplianceReason,
    ComplianceResult,
    check_overtake_legality,
    check_power_limit,
)
from kyntra.regulations.loader import load_fia_2026_config
from kyntra.regulations.models import EventRegulationConfig, FIARegulationConfig

logger = logging.getLogger(__name__)


class EnergySimulator:
    """Deterministic, regulation-constrained F1 hybrid energy simulator.

    Simulates the 4.0 MJ Energy Store usable state-of-charge capacity window
    defined in FIA 2026 Technical Regulations (Article 5.2.2) and enforces
    speed-dependent MGU-K power tapering (Article 5.4.8/5.4.9) and per-lap
    recharge ceilings (Article 5.3.3 and official Event Notes).
    """

    def __init__(
        self,
        regulation_config: Optional[FIARegulationConfig] = None,
        event_config: Optional[EventRegulationConfig] = None,
        harvest_config: Optional[HarvestModelConfig] = None,
        policy_config: Optional[ActionPolicyConfig] = None,
    ):
        self.reg_config = regulation_config or load_fia_2026_config()
        if event_config is not None:
            self.reg_config.apply_event_config(event_config)
        self.event_config = self.reg_config.event_config
        self.harvest_config = harvest_config or DEFAULT_HARVEST_CONFIG
        self.policy_config = policy_config or DEFAULT_ACTION_POLICY
        self.usable_window_mj = self.reg_config.energy_store_usable_window_mj
        self.max_recharge_limit_mj = self.reg_config.get_effective_recharge_limit_mj()


    def initialize_state(
        self,
        initial_energy_fraction: float = 0.50,
        start_lap: int = 1,
        start_sector: int = 1,
        start_time: Optional[timedelta] = None,
    ) -> EnergyState:
        """Create an initial scenario energy state.

        IMPORTANT:
        Actual battery SOC is unknown in public telemetry.
        initial_energy_fraction is a scenario input (e.g. 0.25, 0.50, 0.75).

        Args:
            initial_energy_fraction: Starting usable battery fraction [0.0 - 1.0].
            start_lap: Lap number.
            start_sector: Sector number.
            start_time: Elapsed session timedelta.

        Returns:
            EnergyState: Initialized state with source = TelemetrySource.SIMULATED.
        """
        if not (0.0 <= initial_energy_fraction <= 1.0):
            raise ValueError(
                f"initial_energy_fraction must be in range [0.0, 1.0], got {initial_energy_fraction}"
            )

        energy_mj = initial_energy_fraction * self.usable_window_mj

        return EnergyState(
            timestamp=start_time or timedelta(0),
            lap=start_lap,
            sector=start_sector,
            energy_available_mj=energy_mj,
            energy_window_fraction=initial_energy_fraction,
            energy_harvested_this_lap_mj=0.0,
            energy_deployed_this_lap_mj=0.0,
            recharge_limit_remaining_mj=self.max_recharge_limit_mj,
            overtake_enabled=self.reg_config.overtake_enabled,
            overtake_eligible=None,
            source=TelemetrySource.SIMULATED,
        )

    def step(
        self,
        current_state: EnergyState,
        speed_kmh: float,
        throttle_pct: float,
        brake: Union[bool, float, int],
        dt_s: float,
        action: TacticalAction = TacticalAction.DEPLOY,
        is_sc_active: bool = False,
        overtake_eligible: Optional[bool] = None,
        lap: int = 1,
        sector: int = 1,
        timestamp: Optional[timedelta] = None,
    ) -> Tuple[EnergyState, ComplianceResult, float, float]:
        """Advance the energy state by time delta dt_s under driver context and tactical action.

        State transition:
            E_next = E_current + step_harvest_mj - step_deploy_mj
            clamped to [0.0, energy_store_usable_window_mj]

        Returns:
            Tuple[EnergyState, ComplianceResult, step_harvest_mj, step_deploy_mj]
        """
        step_time = timestamp or (current_state.timestamp + timedelta(seconds=dt_s))

        # Check if lap transition occurred
        lap_changed = lap > current_state.lap
        lap_harvested_so_far = 0.0 if lap_changed else current_state.energy_harvested_this_lap_mj
        lap_deployed_so_far = 0.0 if lap_changed else current_state.energy_deployed_this_lap_mj

        # 1. Evaluate compliance for requested action
        executed_action = action
        compliance_res = ComplianceResult(
            is_compliant=True,
            reason=ComplianceReason.ALLOWED,
            message="Standard deployment compliant.",
        )

        # Update temporary state for compliance check
        eval_state = current_state.model_copy(
            update={
                "overtake_eligible": overtake_eligible,
                "lap": lap,
                "sector": sector,
            }
        )

        # Update SC condition on regulation config copy
        step_reg_config = self.reg_config.model_copy(update={"safety_car_active": is_sc_active})

        if action == TacticalAction.OVERTAKE:
            overtake_check = check_overtake_legality(step_reg_config, eval_state)
            if not overtake_check.is_compliant:
                # Compliance violation prevented: downgrade to standard DEPLOY
                compliance_res = overtake_check
                executed_action = TacticalAction.DEPLOY
            else:
                compliance_res = overtake_check

        # Resolve effective per-lap recharge ceiling based on tactical state (overtake active vs inactive)
        is_overtake_active = (executed_action == TacticalAction.OVERTAKE)
        step_recharge_limit_mj = step_reg_config.get_effective_recharge_limit_mj(is_overtake_active=is_overtake_active)

        # 2. Compute simulated MGU-K kinetic harvest
        step_harvest_mj = calculate_step_harvest_mj(
            speed_kmh=speed_kmh,
            throttle_pct=throttle_pct,
            brake=brake,
            dt_s=dt_s,
            current_lap_harvested_mj=lap_harvested_so_far,
            max_recharge_limit_mj=step_recharge_limit_mj,
            config=self.harvest_config,
        )

        # 3. Compute target electrical deployment
        target_power_kw = compute_target_deployment_power_kw(
            action=executed_action,
            speed_kmh=speed_kmh,
            throttle_pct=throttle_pct,
            regulation_config=step_reg_config,
            policy_config=self.policy_config,
        )

        # If Safety Car is active, energy deployment is suppressed
        if is_sc_active:
            target_power_kw = 0.0

        # Requested energy delta in MJ (kW * s / 1000)
        requested_deploy_mj = (target_power_kw * dt_s) / 1000.0

        # Usable window constraint: cannot deploy more energy than currently available in ES
        actual_deploy_mj = min(requested_deploy_mj, current_state.energy_available_mj)

        # 4. State transition: E_next = E_curr + harvest - deploy
        raw_e_next = current_state.energy_available_mj + step_harvest_mj - actual_deploy_mj
        # Strictly clamped within [0.0, energy_store_usable_window_mj]
        e_next_mj = max(0.0, min(self.usable_window_mj, raw_e_next))
        fraction_next = e_next_mj / self.usable_window_mj

        # Cumulative lap counters
        new_lap_harvest = lap_harvested_so_far + step_harvest_mj
        new_lap_deploy = lap_deployed_so_far + actual_deploy_mj
        recharge_remaining = max(0.0, step_recharge_limit_mj - new_lap_harvest)


        next_state = EnergyState(
            timestamp=step_time,
            lap=lap,
            sector=sector,
            energy_available_mj=e_next_mj,
            energy_window_fraction=fraction_next,
            energy_harvested_this_lap_mj=new_lap_harvest,
            energy_deployed_this_lap_mj=new_lap_deploy,
            recharge_limit_remaining_mj=recharge_remaining,
            overtake_enabled=step_reg_config.overtake_enabled and not is_sc_active,
            overtake_eligible=overtake_eligible,
            source=TelemetrySource.SIMULATED,
        )

        return next_state, compliance_res, step_harvest_mj, actual_deploy_mj

    def simulate_telemetry_trace(
        self,
        telemetry_df: pd.DataFrame,
        driver: str,
        initial_energy_fraction: float = 0.50,
        default_action: TacticalAction = TacticalAction.DEPLOY,
    ) -> pd.DataFrame:
        """Run continuous energy simulation over a driver's high-frequency telemetry trace.

        Generates a comprehensive simulation dataframe with strict provenance columns.

        Args:
            telemetry_df: Output of extract_driver_telemetry containing Speed, Throttle, Brake, dt_s, etc.
            driver: Driver identifier.
            initial_energy_fraction: Starting scenario usable battery fraction.
            default_action: Tactical action policy to simulate across the stint.

        Returns:
            pd.DataFrame: Simulation trace ready for Parquet export.
        """
        if telemetry_df.empty:
            raise ValueError("Telemetry DataFrame is empty.")

        rows: List[Dict] = []
        state = self.initialize_state(
            initial_energy_fraction=initial_energy_fraction,
            start_lap=int(telemetry_df["LapNumber"].iloc[0]),
            start_time=pd.to_timedelta(telemetry_df["SessionTime"].iloc[0]),
        )

        violations_prevented = 0

        for idx, tel_row in telemetry_df.iterrows():
            lap = int(tel_row["LapNumber"])
            speed = float(tel_row["Speed"]) if pd.notna(tel_row["Speed"]) else 0.0
            throttle = float(tel_row["Throttle"]) if pd.notna(tel_row["Throttle"]) else 0.0
            brake = tel_row["Brake"] if pd.notna(tel_row["Brake"]) else False
            dt_s = float(tel_row["dt_s"]) if "dt_s" in tel_row and pd.notna(tel_row["dt_s"]) else 0.1
            timestamp = pd.to_timedelta(tel_row["SessionTime"])

            # Determine sector (approximate by track distance or default)
            sector = 1

            # Simulated tactical scenario: attempt OVERTAKE when close behind car ahead
            action_for_step = default_action
            overtake_eligible = None
            if "DistanceToDriverAhead" in tel_row and pd.notna(tel_row["DistanceToDriverAhead"]):
                gap_dist = float(tel_row["DistanceToDriverAhead"])
                if 0.0 < gap_dist < 20.0:  # In striking distance (<20m)
                    action_for_step = TacticalAction.OVERTAKE
                    overtake_eligible = True
                elif gap_dist >= 20.0:
                    overtake_eligible = False

            state, comp_res, harvest_mj, deploy_mj = self.step(
                current_state=state,
                speed_kmh=speed,
                throttle_pct=throttle,
                brake=brake,
                dt_s=dt_s,
                action=action_for_step,
                is_sc_active=False,
                overtake_eligible=overtake_eligible,
                lap=lap,
                sector=sector,
                timestamp=timestamp,
            )

            if not comp_res.is_compliant:
                violations_prevented += 1

            rows.append(
                {
                    "timestamp": timestamp,
                    "lap": lap,
                    "driver": str(driver),
                    "speed": speed,
                    "throttle": throttle,
                    "brake": brake,
                    "action": action_for_step.value,
                    "simulated_energy_available_mj": round(state.energy_available_mj, 5),
                    "simulated_energy_fraction": round(state.energy_window_fraction, 5),
                    "simulated_harvest_mj": round(harvest_mj, 6),
                    "simulated_deployment_mj": round(deploy_mj, 6),
                    "recharge_remaining_mj": round(state.recharge_limit_remaining_mj or 0.0, 5),
                    "overtake_enabled": state.overtake_enabled,
                    "overtake_eligible": state.overtake_eligible,
                    "compliance_result": comp_res.reason.value,
                    "telemetry_source": "REAL_FASTF1_TELEMETRY",
                    "energy_source": TelemetrySource.SIMULATED.value,
                }
            )

        logger.info(
            "Completed simulation for driver %s: %d steps, %d compliance interventions",
            driver,
            len(rows),
            violations_prevented,
        )

        trace_df = pd.DataFrame(rows)
        return trace_df
