import { useEffect, useState } from 'react';
import type { BattleWatchlistItem, DecisionSnapshot, EvidenceInspectionTarget, WindowState } from '../../types';
import { AdaptiveIntelligencePanel } from '../analysis/AdaptiveIntelligencePanel';
import { featureValue, metric, modelHash } from '../../domain/presentation';
interface Props { decision:DecisionSnapshot|null; previousDecision?:DecisionSnapshot|null; selectedBattleId:string|null; watchlist:BattleWatchlistItem[]; onSelectBattle:(id:string)=>void; currentWindow?:WindowState|null; onOpenEvidence?:(target:EvidenceInspectionTarget)=>void; decisionHistory?:any[]; judgeFocus?:string }
const FEATURES = ['gap_seconds','closing_rate','recent_pace_delta_1lap','recent_pace_delta_3laps','speed_trap_delta'];
export function AnalysisWorkspace({decision,previousDecision,selectedBattleId,watchlist,onSelectBattle,onOpenEvidence,judgeFocus}:Props) {
  const [tab,setTab] = useState('Model');
  useEffect(()=>{ if(judgeFocus === 'adaptive-panel') setTab('Adaptation'); else if(judgeFocus === 'model-card') setTab('Model'); else if(judgeFocus === 'outcome-ledger') setTab('Validation'); },[judgeFocus]);
  return <div className="astra-workspace astra-analysis">
    <div className="astra-section-heading"><div><span className="astra-eyebrow">04 / INTELLIGENCE</span><h2>The model predicts opportunity. KYNTRA decides strategy.</h2><p>Trained intelligence, adaptive inference, and a traceable decision architecture.</p></div>
      <select aria-label="Analysis battle" value={selectedBattleId || ''} onChange={e=>onSelectBattle(e.target.value)}><option value="" disabled>Select battle</option>{watchlist.map(b=><option key={b.battle_id} value={b.battle_id}>{b.attacker} → {b.defender}</option>)}</select></div>
    <div className="astra-tabs">{['Model','Adaptation','Architecture','Validation'].map(name=><button key={name} onClick={()=>setTab(name)} className={tab===name?'active':''}>{name}</button>)}</div>
    {tab==='Model' && <section data-spotlight="model-card"><div className="astra-model-story"><div><span className="astra-eyebrow">01 / TRAINED INTELLIGENCE</span><h1>Built from battles.<br/>Frozen for race day.</h1><p>Five race-dynamics features enter the same LightGBM model. Three cumulative horizons describe the opportunity to pass.</p><button className="astra-button" onClick={()=>onOpenEvidence?.({title:'Frozen model evidence',value:modelHash(decision) || 'HASH UNKNOWN',status:'INFO',provenance:'FROZEN MODEL',rawObject:{inference:decision?.overtake,matrix:decision?.strategy_matrix?.current_state_summary,hash:modelHash(decision)}})}>Inspect model provenance ↗</button></div>
      <div className="astra-dataset-grid">{[['8,357','PROCESSED OBSERVATIONS'],['1,656','BATTLE SEQUENCES'],['78','DATASET COLUMNS'],['5','MODEL INPUT FEATURES']].map(([value,label])=><div key={label}><strong>{value}</strong><small>{label}</small></div>)}</div></div>
      <div className="astra-pipeline">{['Public race data','Battle extraction','Five features','Frozen LightGBM','P1 / P2 / P3','Validation'].map((label,i)=><div key={label}><small>0{i+1}</small><b>{label}</b>{i<5&&<span>→</span>}</div>)}</div>
      <div className="astra-feature-list">{FEATURES.map((key,i)=><button key={key} onClick={()=>onOpenEvidence?.({title:key,value:metric(featureValue(decision,key)),status:'INFO',provenance:'DERIVED',rawObject:{battle:decision?.battle,current_state:decision?.strategy_matrix?.current_state_summary}})}><small>INPUT 0{i+1}</small><strong>{key.replaceAll('_',' ')}</strong><b>{metric(featureValue(decision,key))}</b></button>)}</div>
      <p className="astra-caption">Dataset counts: reports/overtake_dataset_final_qa.md. PAV enforces horizon ordering P1 ≤ P2 ≤ P3; it is not probability calibration. Circuit-independent input fields do not establish universal circuit generalization.</p></section>}
    {tab==='Adaptation' && <AdaptiveIntelligencePanel decision={decision} previousDecision={previousDecision} onOpenEvidence={onOpenEvidence}/>}
    {tab==='Architecture' && <section><span className="astra-eyebrow">03 / DECISION INTELLIGENCE</span><h2>One specialist. A broader decision architecture.</h2><div className="astra-pipeline architecture">{['World state','Specialist model','Constraints','Counterfactuals','Ranking','Publication gate','Decision','Explanation','Memory'].map((label,i)=><div key={label}><small>{String(i+1).padStart(2,'0')}</small><b>{label}</b></div>)}</div><div className="astra-platform"><div><span className="astra-eyebrow">CURRENT SPECIALIST MODULE</span><h3>Overtake Intelligence</h3><p>Energy-aware racecraft · rules · Stability V1 · four counterfactual futures · decision memory · replay and forensics.</p></div><div><span className="astra-eyebrow">ROADMAP / NOT IMPLEMENTED</span><h3>Additional strategy specialists</h3><p>Tyre strategy · pit windows · undercut / overcut · weather transitions · traffic management · safety-car response · fuel targets · restarts · team model packs · authorized live integrations.</p></div></div></section>}
    {tab==='Validation' && <section data-spotlight="outcome-ledger"><h2>Separate learning, validation, and demonstration.</h2><div className="astra-validation-grid">{[['6,197','Training observations','7 development events. Offline training and event-aware evaluation.'],['2,160','Consumed validation observations','2 events. Used in development; not untouched test data.'],['4','Engineering / demo holdouts','Australia, Japan, Miami, Italy. Deterministic replay sessions, not the full training dataset.']].map(([value,title,description])=><div key={title}><strong>{value}</strong><h3>{title}</h3><p>{description}</p></div>)}</div><p className="astra-caption">Provenance: reports/overtake_dataset_report.md and reports/overtake_dataset_final_qa.md. Counts describe processed observations; usable rows differ by horizon and filtering.</p><div className="astra-notice"><b>Historical outcome ledger</b><p>No verified post-moment outcomes are supplied to this view. It does not generate passes, scores, or retrospective success claims.</p></div><h3>Model evolution · roadmap</h3><p>Offline retraining → historical validation → champion/challenger comparison → human release gate → versioned model pack.</p><p className="astra-caption">Runtime weights stay frozen. The proposed model-release workflow is distinct from adaptation to changing inputs.</p></section>}
  </div>;
}

