import React, { useState } from 'react';
import type { EvidenceInspectionTarget, KyntraRuntimeSnapshot, OperatingMode, SystemStatus } from '../../types';
import { resolveSystemHealthDisplay } from '../../domain/types';
import { metric } from '../../domain/presentation';
interface Props { systemStatus: SystemStatus | null; wsConnected: boolean; totalEventsCount: number; onOpenEvidence?: (target: EvidenceInspectionTarget) => void; operatingMode?: OperatingMode; transportType?: string; latencyMs?: number | null; connectionStatus?: string; runtimeSnapshot?: KyntraRuntimeSnapshot | null }
export function SystemWorkspace({ systemStatus, totalEventsCount, onOpenEvidence, operatingMode = 'REPLAY', transportType, latencyMs, connectionStatus, runtimeSnapshot: snap }: Props) {
  const [tab, setTab] = useState('Health');
  const offline = !snap || connectionStatus === 'OFFLINE' || connectionStatus === 'STALE';
  const verdict = offline ? 'OFFLINE' : resolveSystemHealthDisplay(snap.health.system_health, snap.health.modules);
  const modules = Object.entries(snap?.health?.modules || {});
  const problems = modules.filter(([, m]) => m.status !== 'OPERATIONAL');
  const identities = { ...snap?.model_identities, ...(snap?.published_call as any)?.provenance };
  return <div className="astra-workspace astra-system" data-spotlight="system-matrix">
    <div className="astra-section-heading"><div><span className="astra-eyebrow">05 / SYSTEM TRUST</span><h2>Can I trust KYNTRA right now?</h2><p>One verdict. Every supporting signal available to inspect.</p></div></div>
    <div className={`astra-trust-verdict ${verdict === 'OPERATIONAL' ? 'verified' : 'caution'}`}><span className="astra-eyebrow">CANONICAL HEALTH</span><h1>{verdict}</h1>
      <p>{offline ? 'A current runtime connection is unavailable. Previously received evidence may be stale.' : problems.length ? problems.map(([key, m]) => `${key}: ${(m as any).last_error || m.reason || m.status}`).join(' · ') : 'All reported subsystems are operational.'}</p></div>
    <div className="astra-system-signals">{[['Mode', operatingMode], ['Source', snap?.mode || 'UNKNOWN'], ['Transport', transportType || 'UNKNOWN'], ['Freshness', (snap?.freshness as any)?.status || 'UNKNOWN'], ['Inference latency', metric(snap?.latencies?.inference_ms, ' ms')], ['API round trip', metric(latencyMs, ' ms')]].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>
    <div className="astra-tabs">{['Health', 'Integrity', 'Persistence', 'Provenance'].map(name => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</div>
    {tab === 'Health' && <div className="astra-table-wrap"><table className="astra-table"><thead><tr><th>Subsystem</th><th>Reported state</th><th>Latency</th><th>Freshness</th><th>Last error / reason</th></tr></thead><tbody>{modules.map(([key, m]) => <tr key={key}><td>{key.replaceAll('_', ' ')}</td><td className={m.status === 'OPERATIONAL' ? 'text-legal' : 'text-amber'}>{m.status}</td><td>{metric(m.latency_ms, ' ms')}</td><td>{metric(m.freshness_s, 's')}</td><td>{(m as any).last_error || m.reason || 'None reported'}</td></tr>)}</tbody></table>{!modules.length && <p className="astra-notice">No subsystem diagnostics received.</p>}</div>}
    {tab === 'Integrity' && <div><p className="astra-caption">Identities reported by the current runtime. The browser does not independently attest artifact contents.</p><dl className="astra-identities">{Object.entries(identities).map(([key, value]) => <React.Fragment key={key}><dt>{key.replaceAll('_', ' ')}</dt><dd>{String(value ?? 'UNKNOWN')}</dd></React.Fragment>)}</dl><button className="astra-button" onClick={() => onOpenEvidence?.({ title: 'Runtime integrity identities', value: verdict, status: 'INFO', provenance: 'DERIVED', rawObject: identities })}>Inspect runtime identities ↗</button></div>}
    {tab === 'Persistence' && <div className="astra-prose"><h2>Memory with an explicit record boundary.</h2><p>{totalEventsCount} events are loaded in this browser session. A loaded event count does not prove durable storage.</p><p>Decision store: {snap?.health.modules?.event_store?.status || 'UNKNOWN'}. {(snap?.health.modules?.event_store as any)?.last_error || 'No storage error reported.'}</p><p>Captured comparisons in the interface are session memory. Only records returned by the decision-history endpoint are described as recorded history.</p></div>}
    {tab === 'Provenance' && <div className="astra-prose"><h2>Know what each number means.</h2>{[['Public source', 'Observed historical or authorized live race data. Replay is explicitly historical.'], ['Frozen model', 'P1/P2/P3 are model predictions. Weights do not learn online.'], ['Simulated energy', 'Energy scenarios are modeled; private battery SOC is not measured.'], ['Rules & stability', 'Deterministic constraints and ordinal evidence. UNKNOWN remains UNKNOWN.'], ['Historical outcome', 'Known after the prediction moment. Never input to that earlier inference.']].map(([title, description]) => <p key={title}><strong>{title}</strong><br/>{description}</p>)}<p>Model loaded: {systemStatus?.overtake_model?.loaded == null ? 'UNKNOWN' : systemStatus.overtake_model.loaded ? 'YES' : 'NO'}</p></div>}
  </div>;
}

